#!/bin/bash
# This script needs to be run from the testsuite/mpi directory

# Customization for the HET cluster at the University of Colorado
makefile=Make_mpi
run="/usr/local/mpich2-1.4.1p1/bin/mpirun -np 2"

# Currently only one application directory and target
# User just needs to specify NCOL, DIMF and fermion irrep
if [ $# -lt 4 ]; then
  echo "Try these:"
  echo "./run_tests su3_hmc 2 2 FUNDAMENTAL"
  echo "./run_tests su3_hmc 3 3 FUNDAMENTAL"
  echo "./run_tests su3_hmc_spectrum 3 3 FUNDAMENTAL"
  echo "./run_tests su3_hmc 3 6 SYMMETRIC2"
  echo "./run_tests su3_hmc 4 4 FUNDAMENTAL"
  echo "./run_tests su3_hmc 4 6 ANTISYMMETRIC2"
  exit 0
fi

target=$1
N=$2
DIMF=$3
rep=$4

if [[ "$rep" == "FUNDAMENTAL" ]] ; then
  tag='F'
elif [[ "$rep" == "SYMMETRIC2" ]] ; then
  tag='S'
elif [[ "$rep" == "ANTISYMMETRIC2" ]] ; then
  tag='A'
else
  echo "Error: Unrecognized rep $rep"
  exit 1
fi

outpat=${target#su3_} # Omit 'su3_' from output file

# Change N and rep in include/su3.h
cd ../../clover_hmc/
sed -i -E "s/(#define NCOL) .*/\1 $N/" ../include/su3.h
sed -i -E "s/(#define DIMF) .*/\1 $DIMF/" ../include/su3.h
sed -i -E "s/(#define FREP) .*/\1 $rep/" ../include/su3.h

# Change rep in clover_hmc/Make_template
if [[ "$rep" == "SYMMETRIC2" ]] ; then
  sed -i -E "s/chain_rule_f/chain_rule_sym_2/" Make_template
  sed -i -E "s/fermion_rep_f/fermion_rep_sym_2/" Make_template
elif [[ "$rep" == "ANTISYMMETRIC2" ]] ; then
  sed -i -E "s/chain_rule_f/chain_rule_as_2/" Make_template
  sed -i -E "s/fermion_rep_f/fermion_rep_as_2/" Make_template
fi

# Compile
echo "Compiling $target..."
if ! make -f $makefile $target >& /dev/null ; then
  echo "ERROR: $target compilation failed"
  make -f $makefile $target
  exit
fi

# Reset N and rep to SU(3) fundamental
sed -i -E "s/(#define NCOL) .*/\1 3/" ../include/su3.h
sed -i -E "s/(#define DIMF) .*/\1 3/" ../include/su3.h
sed -i -E "s/(#define FREP) .*/\1 FUNDAMENTAL/" ../include/su3.h

# Reset fundamental rep in clover_hmc/Make_template
if [[ "$rep" == "SYMMETRIC2" ]] ; then
  sed -i -E "s/chain_rule_sym_2/chain_rule_f/" Make_template
  sed -i -E "s/fermion_rep_sym_2/fermion_rep_f/" Make_template
elif [[ "$rep" == "ANTISYMMETRIC2" ]] ; then
  sed -i -E "s/chain_rule_as_2/chain_rule_f/" Make_template
  sed -i -E "s/fermion_rep_as_2/fermion_rep_f/" Make_template
fi

# Run
cd ../testsuite/
rm -f mpi/$outpat.$N$tag.out
echo "Running $target..."
$run ../clover_hmc/$target < in.$N$tag.hmc > mpi/$outpat.$N$tag.out

# Check
cd mpi/
d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' $outpat.$N$tag.ref $outpat.$N$tag.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "$outpat.$N$tag.ref and $outpat.$N$tag.out differ:"
  echo "$d"
else
  echo "PASS: $target reproduces reference output for SU($N) $rep"
fi
exit
