#!/bin/bash
# This script needs to be run from the testsuite/mpi directory

# May need to be customized for different platforms
makefile=Make_mpi
run="mpirun -np 2"

# TODO: Should eventually merge into a single script
# User just needs to specify NCOL
if [ $# -lt 1 ]; then
  echo "Usage: $0 <N>"
  exit 0
fi

tag=ora
target=pg_ora
N=$1

# Change N in include/su3.h
# Set DIMF to 99 to make sure it doesn't matter
cd ../../pure_gauge/
sed -i -E "s/(#define NCOL) .*/\1 $N/" ../include/su3.h
sed -i -E "s/(#define DIMF) .*/\1 99/" ../include/su3.h

# Compile
echo "Compiling $target..."
if ! make -f $makefile $target >& /dev/null ; then
  echo "ERROR: $target compilation failed"
  make -f $makefile $target
  exit
fi

# Reset N and DIMF to 3
sed -i -E "s/(#define NCOL) .*/\1 3/" ../include/su3.h
sed -i -E "s/(#define DIMF) .*/\1 3/" ../include/su3.h

# Run
cd ../testsuite/
rm -f mpi/$tag.$N.out
echo "Running $target..."
$run ../pure_gauge/$target < in.$N.$tag > mpi/$tag.$N.out

# Check
cd mpi/
d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' $tag.$N.ref $tag.$N.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "$tag.$N.ref and $tag.$N.out differ:"
  echo "$d"
else
  echo "PASS: $target reproduces reference output for SU($N)"
fi
exit
