#!/bin/bash
# This script needs to be run from the testsuite/scalar directory

# Currently only one application directory and target
# User just needs to specify NCOL, DIMF and fermion irrep
if [ $# -lt 2 ]; then
  echo "Try these:"
  echo "./run_tests 3 3 fundamental"
  echo "./run_tests 3 6 symmetric2"
  echo "./run_tests 4 4 fundamental"
  echo "./run_tests 4 6 antisymmetric2"
  exit 0
fi

N=$1
DIMF=$2
rep=$3

if [[ "$rep" == "fundamental" ]] ; then
  tag='F'
elif [[ "$rep" == "symmetric2" ]] ; then
  tag='S'
elif [[ "$rep" == "antisymmetric2" ]] ; then
  tag='A'
else
  echo "Error: Unrecognized rep $rep"
  exit 1
fi

# Change N and rep
# TODO: Also need different fermion_rep_*.o in clover_hmc/Make_template
cd ../../include/
awk -v"X=#define NCOL $N" '{sub(/^#define NCOL .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
awk -v"X=#define DIMF $DIMF" '{sub(/^#define DIMF .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
awk -v"X=#define FREP $rep" '{sub(/^#define FREP .*/,X);print}' su3.h > TEMP && mv TEMP su3.h

# Compile
cd ../clover_hmc/
echo "Compiling su3_hmc..."
if ! make -f Make_scalar su3_hmc >& /dev/null ; then
  echo "ERROR: su3_hmc compilation failed"
  make -f Make_scalar su3_hmc
  exit
fi

# Reset N and rep to SU(3) fundamental
# TODO: Also need different fermion_rep_*.o in clover_hmc/Make_template
cd ../include/
awk -v"X=#define NCOL 3" '{sub(/^#define NCOL .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
awk -v"X=#define DIMF 3" '{sub(/^#define DIMF .*/,X);print}' su3.h > TEMP && mv TEMP su3.h
awk -v"X=#define FREP fundamental" '{sub(/^#define FREP .*/,X);print}' su3.h > TEMP && mv TEMP su3.h

# Run
cd ../testsuite/
rm -f scalar/hmc.$N$tag.out
echo "Running su3_hmc..."
../clover_hmc/su3_hmc < in.$N$tag.hmc > scalar/hmc.$N$tag.out

# Check
cd scalar/
d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' hmc.$N$tag.ref hmc.$N$tag.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "hmc.$N$tag.ref and hmc.$N$tag.out differ:"
  echo "$d"
else
  echo "PASS: su3_hmc reproduces reference output for SU($N) $rep"
fi
exit
