#!/bin/bash
# This script needs to be run from the testsuite/scalar directory

# TODO: Should eventually merge into a single script
# For now user just needs to specify NCOL
if [ $# -lt 1 ]; then
  echo "Usage: $0 <N>"
  exit 0
fi

N=$1

# Change N in include/su3.h
cd ../../wilson_flow/
sed -i -E "s/(#define NCOL) .*/\1 $N/" ../include/su3.h

# Compile
echo "Compiling su3_Wflow..."
if ! make -f Make_scalar su3_Wflow >& /dev/null ; then
  echo "ERROR: su3_Wflow compilation failed"
  make -f Make_scalar su3_Wflow
  exit
fi

# Reset N to 3
sed -i -E "s/(#define NCOL) .*/\1 3/" ../include/su3.h

# Run
cd ../testsuite/
rm -f scalar/Wflow.$N.out
echo "Running su3_Wflow..."
../wilson_flow/su3_Wflow < in.$N.Wflow > scalar/Wflow.$N.out

# Check
cd scalar/
d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' Wflow.$N.ref Wflow.$N.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "Wflow.$N.ref and Wflow.$N.out differ:"
  echo "$d"
else
  echo "PASS: su3_Wflow reproduces reference output for SU($N) $rep"
fi
exit
